[project]
name = "mini-jukebox"
version = "0.1.0"
description = "Yet another Discord music bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.4.0",
    "lyricsgenius>=3.2.0",
    "packaging>=24.2",
    "pynacl>=1.5.0",
    "yt-dlp>=2025.1.26",
]
